### ISSUE TITLE
error running in example code

### ISSUE THREAD

**Issue by sumin5784** [sigven/oncoEnrichR#37]
**Describe the bug**
I installed the package and ran the example code in document, and I got this error. I tried with other query gene sets but the error was the same.

```
INFO  [2025-02-20 13:14:18] WARNING: target gene identifiers NOT found as primary symbols: CCDC101, SMEK1, MGEA5, DGCR14
INFO  [2025-02-20 13:14:18] Trying to map target gene identifiers as gene aliases/synonyms: CCDC101, SMEK1, MGEA5, DGCR14
INFO  [2025-02-20 13:14:18] Mapped query identifiers as gene aliases CCDC101, SMEK1, MGEA5, DGCR14 ---> SGF29, PPP4R3A, OGA, ESS2
INFO  [2025-02-20 13:14:18] SUCCESS: Identified all genes (n = 134) in target set
INFO  [2025-02-20 13:14:18] Open Targets Platform: annotation of protein targets to disease phenotypes (minimum association score =  0.05)
INFO  [2025-02-20 13:14:18] Open Targets Platform: annotation of protein targets to targeted drugs (cancer indications only)
INFO  [2025-02-20 13:14:18] Open Targets Platform: annotation of target tractabilities (druggability)
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA: performing gene enrichment analysis of target set with clusterProfiler
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA clusterProfiler settings: p_value_cutoff = 0.05, q_value_cutoff = 0.2
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA clusterProfiler settings: p_value_adjustment_method = BH
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA clusterProfiler settings: minGSSize = 10
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA clusterProfiler settings: maxGSSize = 500
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA clusterProfiler settings: Background geneset: 'All protein-coding genes'
INFO  [2025-02-20 13:14:18] MSIGdb/H/ALL - Enrichment/ORA clusterProfiler settings: Background geneset size = 20599
Error in `dplyr::rename()`:
! Can't rename columns that don't exist.
x Column `RichFactor` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
```

1. The version of *oncoEnrichR* used: oncoEnrichR_1.5.2
2. The queryset used (gene identifiers): I ran example code in document
3. The complete set options (explicitly) set when running *oncoEnrichR*: I ran example code in document (see below)

```
library(oncoEnrichR)
myc_interact_targets <- read.csv(system.file("extdata","myc_data.csv", package = "oncoEnrichR"), stringsAsFactors = F)
oeDB <- oncoEnrichR::load_db(cache_dir = "<LOCAL_FOLDER>")
myc_report <- oncoEnrichR::onco_enrich(
  query = myc_interact_targets$symbol, 
  oeDB = oeDB, 
  project_title = "cMYC BioID screen", 
  project_owner = "Raught et al."
  )
oncoEnrichR::write(report = myc_report, oeDB = oeDB, file = "<LOCAL_FOLDER>/myc_report_oncoenrichr.html", format = "html")
oncoEnrichR::write(report = myc_report, oeDB = oeDB, file = "<LOCAL_FOLDER>/myc_report_oncoenrichr.xlsx", format = "excel")
```

I didn't have this error with galaxy, I don't know why. 
Could you please check this? I want to R package instead using galaxy.

Thanks,
Sumin

**Comment by sigven** [comment]
Hi Sumin,

Thanks for reaching out. I am aware of this one, suspect it has to do with the version of `clusterProfiler` that is being used. Can you check your version of that package and report back?

best,
Sigve

**Comment by sumin5784** [comment]
Hi, Sigve

Thanks for the quick response.
I'm afraid but I can't find the clusterProfiler package even though I attached onroEnrichR package.


attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] oncoEnrichR_1.5.2

loaded via a namespace (and not attached):
 [1] circlize_0.4.16       shape_1.4.6.1         GetoptLong_1.0.5      tidyselect_1.2.0
 [5] xfun_0.39             purrr_1.0.1           reshape2_1.4.4        colorspace_2.1-0
 [9] vctrs_0.6.5           generics_0.1.3        htmltools_0.5.8.1     stats4_4.1.3
[13] yaml_2.3.7            rlang_1.1.5           pillar_1.10.1         glue_1.6.2
[17] BiocGenerics_0.40.0   RColorBrewer_1.1-3    readxl_1.4.2          matrixStats_0.63.0
[21] foreach_1.5.2         lifecycle_1.0.4       plyr_1.8.8            stringr_1.5.1
[25] munsell_0.5.1         gtable_0.3.6          cellranger_1.1.0      GlobalOptions_0.1.2
[29] codetools_0.2-18      evaluate_1.0.3        knitr_1.45            ComplexHeatmap_2.10.0
[33] IRanges_2.28.0        fastmap_1.1.1         doParallel_1.0.17     parallel_4.1.3
[37] Rcpp_1.0.10           scales_1.3.0          writexl_1.4.2         S4Vectors_0.32.4
[41] rjson_0.2.21          ggplot2_3.5.1         png_0.1-8             digest_0.6.31
[45] stringi_1.7.12        dplyr_1.1.4           grid_4.1.3            clue_0.3-64
[49] ggvenn_0.1.10         cli_3.6.1             tools_4.1.3           magrittr_2.0.3
[53] tibble_3.2.1          cluster_2.1.4         crayon_1.5.3          tidyr_1.3.0
[57] pkgconfig_2.0.3       rmarkdown_2.29        rstudioapi_0.17.1     iterators_1.0.14
[61] R6_2.6.0              compiler_4.1.3


So, I tried installing clusterProfiler package manually but there were dependency issues, requiring me to install aplot package, and it induced another error, and so on. I'm using R 4.1.3 now, but I can try with R 4.2 if you want.



Best,
Sumin






________________________________

**Comment by sigven** [comment]
Hi, Sumin,

Thanks for the feedback. If you are using RStudio, you should be able to see which version of clusterProfiler that have been installed?

Either way, I would suggest upgrading the R version; and either way truly sorry for the inconvience. I am struggling somewhat to make a given version work stable across different R versions, this is also particularly challenging for oncoEnrichR given the large number of package dependencies. But users have been able to use v5.2 successfully, so I suspect that if you can successfully upgrade your `clusterProfiler` package, it should be working better.. (time will show:))

PS. Reason that this error is not showing for Galaxy, is that it Galaxy is still running a slightly older version (non-quarto based). The quarto-based version of oncoEnrichR (5.x) is not yet operational within Galaxy.

best,
Sigve

**Comment by sumin5784** [comment]
Hi Sigve,

As you recommended, I updated R 4.1 to R 4.2.3 and installed oncoEnrichR package. However, I still have the same error message, complaining about RichFactor. The Version of clusterProfiler is v4.6.2. Any other options that I can try?



Regards,
Sumin



________________________________

**Comment by sigven** [comment]
Hi Sumin,

Perhaps upgrade `clusterProfiler` to it's latest version? I will try to bump a new version soon that you can test also.

best,
Sigve

**Comment by sigven** [comment]
Try new release, that should work, I think. Closing for now.

**Comment by sumin5784** [comment]
Hi Sigven,

I installed new release but got this error, is it the same clusterProfiler issue?:


Error in `dplyr::rename()`:
! Can't rename columns that don't exist.
✖ Column `zScore` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.



I used R version and these are clusterProfiler and oncoEnrichR versions:
[clusterProfiler_4.6.2 oncoEnrichR_1.5.3





________________________________

**Comment by sigven** [comment]
Hi Sumin,
Yeah you need to upgrade ClusterProfiler. Your version 4.6.2 is too old version for oncoEnrichR to work properly. I've tried to set this as a requiment in the `DESCRIPTION` file (clusterProfiler > v4.13), but apparently that's not sufficient to make it install the correct versions. I would actually recommend that you upgrade your BioConductor version (https://bioconductor.org/install/), you're probably having an older version running? 

best,
Sigve
